GET http://127.0.0.1:1234/order
Content-Type: application/json

###
GET http://127.0.0.1:1234/order/2020-04-06-01
Content-Type: application/json

###
GET http://127.0.0.1:1234/order/2020-04-06-01/total
Content-Type: application/json